spring:
  datasource:
      url: jdbc:mysql://localhost:3306/springboot_shiro_vue?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: admin123
mybatis:
   mapperLocations: classpath:/mapper/*.xml
